name: Multi-Platform Build Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            arch_label: x64
          - os: windows-11-arm
            arch_label: arm64

          - os: macos-15-intel
            arch_label: x86_64
          - os: macos-latest
            arch_label: arm64

          - os: ubuntu-latest
            arch_label: x86_64
          - os: ubuntu-24.04-arm
            arch_label: aarch64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Variables from Makefile
        shell: bash
        run: |
          APP_NAME=$(grep -E '^APP_NAME\s*=' Makefile | cut -d '=' -f2 | xargs)
          APP_VERSION=$(grep -E '^APP_VERSION\s*=' Makefile | cut -d '=' -f2 | xargs)
          echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt
        shell: bash

      - name: Build Test
        run: |
          python -m nuitka --assume-yes-for-downloads --standalone --onefile --include-data-dir=src/ui=ui --output-dir=build --output-filename="test-${{ matrix.arch_label }}" src/main.py
        shell: bash
