name: Build and Publish Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            arch: x86
            suffix: exe
          - os: windows-11-arm
            arch: arm64
            suffix: exe

          - os: macos-15-intel
            arch: x86
            suffix: dmg
          - os: macos-latest
            arch: aarch64
            suffix: dmg

          - os: ubuntu-latest
            arch: x86
            suffix: flatpak
          - os: ubuntu-24.04-arm
            arch: arm64
            suffix: flatpak

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental == true }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Extract App Variables
        shell: bash
        run: |
          APP_NAME=$(grep -E '^APP_NAME\s*=' Makefile | cut -d '=' -f2 | xargs)
          COMPANY_NAME=$(grep -E '^COMPANY_NAME\s*=' Makefile | cut -d '=' -f2 | sed 's/"//g' | xargs)

          APP_VERSION=${GITHUB_REF_NAME#v}

          CLEAN_COMPANY=$(echo "$COMPANY_NAME" | tr '[:upper:]' '[:lower:]' | tr -d ' ')
          CLEAN_APP=$(echo "$APP_NAME" | tr '[:upper:]' '[:lower:]' | tr -d ' ')

          echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
          echo "COMPANY_NAME=$COMPANY_NAME" >> $GITHUB_ENV
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
          echo "FLATPAK_ID=com.$CLEAN_COMPANY.$CLEAN_APP" >> $GITHUB_ENV

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Tooling
        run: pip install nuitka slint zstandard

      - name: Build Windows
        if: runner.os == 'Windows'
        run: |
          python -m nuitka --assume-yes-for-downloads --standalone --onefile --include-data-dir=src/ui=ui --output-dir=dist --windows-product-name="${{ env.APP_NAME }}" --windows-product-version="${{ env.APP_VERSION }}" --windows-company-name="${{ env.COMPANY_NAME }}" --output-filename="${{ env.APP_NAME }}-v${{ env.APP_VERSION }}-${{ matrix.arch }}.exe" src/main.py

      - name: Build macOS
        if: runner.os == 'macOS'
        run: |
          python -m nuitka --standalone --include-data-dir=src/ui=ui --output-dir=dist --macos-create-app-bundle --macos-app-name="${{ env.APP_NAME }}" --output-filename="${{ env.APP_NAME }}" src/main.py

          # Correção: O Nuitka sempre gera a pasta base como 'main.app' por causa do src/main.py
          mv "dist/main.app" "dist/AppContent.app"
          hdiutil create -volname "${{ env.APP_NAME }}" -srcfolder "dist/AppContent.app" -ov -format UDZO "dist/${{ env.APP_NAME }}-v${{ env.APP_VERSION }}-${{ matrix.arch }}.dmg"

      - name: Build Linux & Flatpak
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update && sudo apt-get install flatpak flatpak-builder ccache -y
          python -m nuitka --assume-yes-for-downloads --standalone --onefile --include-data-dir=src/ui=ui --output-dir=dist --output-filename="${{ env.APP_NAME }}-v${{ env.APP_VERSION }}-${{ matrix.arch }}.bin" src/main.py

          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          sed -i "s/{{FLATPAK_ID}}/${{ env.FLATPAK_ID }}/g" flatpak-manifest.yml
          sed -i "s/{{APP_BIN}}/${{ env.APP_NAME }}-v${{ env.APP_VERSION }}-${{ matrix.arch }}.bin/g" flatpak-manifest.yml

          flatpak-builder --user build-dir flatpak-manifest.yml --force-clean --install-deps-from=flathub
          flatpak build-export repo build-dir
          flatpak build-bundle repo "dist/${{ env.APP_NAME }}-v${{ env.APP_VERSION }}-${{ matrix.arch }}.flatpak" ${{ env.FLATPAK_ID }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            dist/*.exe
            dist/*.dmg
            dist/*.flatpak
            dist/*.bin

  publish_release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download
        uses: actions/download-artifact@v4
        with:
          path: all-artifacts
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: all-artifacts/*
          generate_release_notes: true
